[project]
name = "data_ingestion"
version = "0.1.0"
description = "Load data from file, detect and load change."
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "adbc-driver-sqlite>=1.12.0",
    "duckdb>=1.5.5",
    "fastexcel>=0.20.2",
    "greenlet>=3.5.4",
    "ipykernel>=7.3.0",
    "loguru>=0.7.3",
    "numpy>=2.4.6",
    "pandas>=3.0.5",
    "pip>=26.1.2",
    "polars>=1.43.0",
    "pyarrow>=25.0.0",
    "pydantic>=2.13.4",
    "pytest>=9.1.1",
    "python-dotenv>=1.2.2",
    "ruff>=0.15.22",
    "sqlalchemy>=2.0.51",
    "tzdata>=2026.3",
]
